const assert=require("node:assert");const fs=require("node:fs");const path=require("node:path");const {pathToFileURL}=require("node:url");
(async()=>{const core=await import(pathToFileURL(path.resolve("supabase/functions/hunt-boom-media-vault/vault-core.mjs")));
const p=core.planVaultAsset({source_verified:true,generation_completed:true,mission_id:"BF-IL-0001",asset_id:"S2-4",product_item_id:"CJ-1",mime_type:"video/mp4",duration_seconds:3,aspect_ratio:"9:16",product_truth_verified_at:"2026-09-17T19:00:00Z"});
assert.equal(p.storage_bucket,"boom-media-vault");assert.equal(p.public_url,null);assert.equal(p.private_only,true);assert.match(p.storage_path,/^missions\/BF-IL-0001\/S2-4\.mp4$/);
assert.equal(core.previewTTL(60),60);assert.throws(()=>core.previewTTL(121),/PREVIEW_TTL_INVALID/);assert.equal(core.validateTaskId("task_12345678"),"task_12345678");assert.equal(core.ownerDecision("APPROVE"),"approve");assert.equal(core.ownerDecision("reject"),"reject");assert.throws(()=>core.ownerDecision("publish"),/OWNER_DECISION_INVALID/);assert.equal(core.decisionNote("ok"),"ok");assert.throws(()=>core.decisionNote("x".repeat(501)),/OWNER_DECISION_NOTE_TOO_LONG/);
assert.throws(()=>core.planVaultAsset({source_verified:false,generation_completed:true}),/PRODUCT_TRUTH_REVERIFY_REQUIRED/);assert.throws(()=>core.assertTransition("STORED_PENDING_QA","OWNER_APPROVED"),/VAULT_TRANSITION_BLOCKED/);assert(core.assertTransition("QA_PASSED","OWNER_APPROVED"));
const good=core.postGenerationQA({stored_private:true,aspect_ratio:"9:16",duration_seconds:3,product_fidelity:true,no_unverified_claims:true,no_fake_reviews:true,no_unintended_branding:true,no_major_visual_defects:true,visual_qa_passed:true});
assert.equal(good.status,"QA_PASSED");assert.equal(good.publishing_allowed,false);assert.equal(good.owner_approval_required,true);
const bad=core.postGenerationQA({...good,stored_private:true,aspect_ratio:"9:16",duration_seconds:3,product_fidelity:false,no_unverified_claims:true,no_fake_reviews:true,no_unintended_branding:true,no_major_visual_defects:true,visual_qa_passed:true});assert.equal(bad.status,"QA_FAILED");assert(bad.failed_gates.includes("product_fidelity"));
const sql=fs.readFileSync(globMig(),"utf8");assert(sql.includes("'boom-media-vault'"));assert(sql.includes("public = false"));assert(sql.includes("creative_asset_id text not null"));assert(sql.includes("byte_size bigint not null"));assert(sql.includes("unique (mission_id, creative_asset_id)"));assert(sql.includes("visual_qa_json jsonb"));assert(sql.includes("visual_qa_model text"));assert(sql.includes("qa_completed_at timestamptz"));assert(sql.includes("owner_decision_by uuid"));assert(sql.includes("owner_decided_at timestamptz"));assert(sql.includes("enable row level security"));assert(sql.includes("grant select, insert, update on table public.boom_media_assets to service_role"));assert(sql.includes("grant select on table public.boom_media_assets to authenticated"));assert(!/for insert\s+to authenticated/i.test(sql),"client insert policy must not exist");
const edge=fs.readFileSync("supabase/functions/hunt-boom-media-vault/index.ts","utf8");assert(edge.includes('action==="ingest_runway"'));assert(edge.includes('action==="private_preview"'));assert(edge.includes('action==="visual_qa_plan"'));assert(edge.includes('action==="visual_qa_analyze"'));assert(!edge.includes('action==="visual_qa_commit"'));assert(edge.includes('action==="qa_commit"'));assert(edge.includes('action==="owner_decision"'));assert(edge.includes("status=eq."));assert(edge.includes("crypto.subtle.digest"));assert(edge.includes("/storage/v1/object/sign/"));assert(edge.includes("RUNWAY_TASK_URL"));assert(!edge.includes("source_url"));assert(!edge.includes("publicUrl"));console.log("boom_media_vault_tests=PASS");
function globMig(){return fs.readdirSync("supabase/migrations").filter(x=>x.includes("boom_media_vault.sql")).sort().pop().replace(/^/,"supabase/migrations/")}
})().catch(e=>{console.error(e);process.exit(1)});
