const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-stylist-academy-contract.json","utf8"));
const lighting=JSON.parse(fs.readFileSync("evidence/HUNT-CINEMATIC-LIGHTING-QA-2026-09-22.json","utf8"));
const visual3=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-F35-VISUAL-QA-ROUND3-2026-09-22.json","utf8"));
assert.equal(c.version,"BOOM-STYLIST-ACADEMY-V3");
assert.equal(c.mode,"SHADOW_TRAINING");
assert.equal(c.production_influence,false);
assert.equal(c.autonomous_shelf_reorder,false);
assert.equal(c.publishing_authorized,false);
assert(c.tracks.some(x=>x.id==="S2"));
assert(c.tracks.some(x=>x.id==="M1"));
assert(c.tracks.some(x=>x.id==="M3"));
assert(c.exams.every(x=>x.pass_score===85));
assert(c.exams.some(x=>x.id==="DEPARTMENT-6-LAYER-SURVEY"));
assert(c.exams.some(x=>x.id==="CINEMATIC-LIGHTING-2THEME"));
assert(c.safety_and_trust.some(x=>x.includes("Do not critique")));
assert(c.mastery[c.mastery.length-1].requirement.includes("Owner Gate"));
assert.equal(c.preference_layers.length,6);
assert.equal(c.department_learning.length,17);
assert.equal(c.multidisciplinary_curriculum.length,10);
assert.equal(c.current_state.mastery_level,0);
assert.equal(c.current_state.completed_exams,0);
assert.equal(c.current_state.course_completion,"NOT_CLAIMED");
assert.equal(c.current_state.survey_layers,6);
assert.equal(c.current_state.departments_mapped,17);
assert(c.current_state.training_dataset.includes("37_VERIFIED_PRODUCTS_IL"));
assert.equal(c.current_state.assortment_gate_il,"PASS_4_FOOTWEAR_6_BOTTOMS");
assert.equal(c.current_state.product_truth_round2,"PASS_IL");
assert.equal(c.current_state.cinematic_lighting,"LIGHT_DARK_RENDER_PAIR_VERIFIED");
assert.equal(c.current_state.cinematic_lighting_qa,"V16_LIGHT_DARK_QA_PASS");
assert.equal(c.current_state.cinematic_lighting_mastery,"TRAINING_EVIDENCE_ONLY");
assert.equal(c.current_state.visual_qa_round3,"4_CONTINUE_1_REWORK");
assert.equal(c.current_state.looks_ready,4);
assert.equal(c.current_state.looks_rework,1);
assert(c.brand_case_study_policy.blocked.includes("Do not copy"));
assert.equal(lighting.production_effect,false);
assert.equal(lighting.renders.light.result,"PASS");
assert.equal(lighting.renders.dark.result,"PASS");
assert.equal(lighting.same_product_cross_theme.product_image_fidelity,"PASS");
assert.equal(lighting.stylist_learning.mastery_change,false);
assert.equal(visual3.production_effect,false);
assert.equal(visual3.mastery_change,false);
assert.equal(visual3.counters.looks_can_continue,4);
assert.equal(visual3.counters.looks_rework,1);
const html=fs.readFileSync("boom-brain-studio.html","utf8");
const js=fs.readFileSync("boom-brain-studio.js","utf8");
assert(html.includes('id="bs-stylist-academy"'));
assert(js.includes("async function renderStylistAcademy()"));
assert(js.includes("HUNT-STYLIST-ACADEMY-TRAINING-SET-V3-IL-2026-09-22.json"));
assert(js.includes("HUNT-STYLIST-F35-ROUND2-2026-09-22.json"));
assert(js.includes("HUNT-STYLIST-F35-VISUAL-QA-ROUND3-2026-09-22.json"));
assert(js.includes("HUNT-CINEMATIC-LIGHTING-QA-2026-09-22.json"));
assert(js.includes("M3 · Cinematic Lighting"));
assert(js.includes("Visual QA · 5 Looks"));
console.log("PASS boom-stylist-academy-v3");
