const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));

const s7=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE7-FINAL-PREVIEW-2026-09-23.json");
const qa=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-QA-SHORTLIST-V2-2026-09-23.json");
const ship=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-SHIPPING-VERIFY-2026-09-23.json");
const qp=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-QUALITY-PROFIT-GATE-2026-09-23.json");
const visual=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-VISUAL-QA-2026-09-23.json");
const belts=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-BELT-GATE-2026-09-23.json");
const beltVisual=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-BELT-VISUAL-QA-2026-09-23.json");
const preview=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-COMBINED-ADMISSION-PREVIEW-2026-09-23.json");
const ext=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-EXTERNAL-SOURCE-MANIFEST-2026-09-23.json");
const cj=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-CJ-OFFICE-VERIFY-2026-09-23.json");

for(const x of [qa,ship,qp,visual,belts,beltVisual,preview,ext,cj])assert.equal(x.production_effect,false);
assert.equal(preview.summary.stage7_canonical_products,s7.summary.canonical_products);
assert.equal(preview.summary.shadow_admitted,(visual.summary.visually_approved||0)+(beltVisual.summary.visually_approved||0));
assert.equal(preview.summary.canonical_products_shadow,s7.summary.canonical_products+preview.summary.shadow_admitted);
assert.equal(preview.summary.final_net_profit_verified_products,0);
assert.equal(ext.summary.empty_rails,preview.summary.rails_empty);
assert.equal(ext.rails.length,preview.summary.rails_empty);
assert(ext.rails.every(x=>x.hypersku_state==="MANUAL_SOURCING_REQUEST_RECOMMENDED"));
assert.equal(ship.summary.final_net_profit_verified_products,0);
assert.equal(qp.summary.final_net_profit_verified_products,0);
assert.equal(belts.summary.final_net_profit_verified_products,0);
assert.equal(cj.status,"NO_SINGLE_VARIANT_4_OF_4");
assert(preview.admitted.every(x=>x.visual_state==="PASS_CATEGORY_VISUAL"));
assert(preview.admitted.every(x=>x.final_net_profit_verified===false));
console.log("Product Placement Stage8 Supplier Recovery Visual-Strict: PASS");
