const fs=require("fs"),assert=require("assert");
const e=JSON.parse(fs.readFileSync("evidence/HUNT-EPROLO-GLOBAL-PRODUCT-MARKET-SHELF-2026-09-23.json","utf8"));
const gate=JSON.parse(fs.readFileSync("boom-country-market-gate-contract.json","utf8"));
const routing=JSON.parse(fs.readFileSync("boom-hunt-taxonomy-stylist-routing-contract.json","utf8"));
assert.equal(e.version,"HUNT-EPROLO-GLOBAL-PRODUCT-MARKET-SHELF-V2");
assert.equal(e.mode,"GLOBAL_TAXONOMY_SHADOW_SHELF");
assert.equal(e.production_effect,false);
assert.equal(e.summary.products,15);
assert.equal(e.summary.departments_represented,5);
assert.equal(e.summary.category_shelves_represented,7);
assert.equal(e.summary.countries_represented,33);
assert.equal(e.summary.possible_product_market_pairs,495);
assert.equal(e.summary.shipping_shadow_product_market_pairs,455);
assert.equal(e.summary.policy_mapped_shadow_pairs,281);
assert.equal(e.summary.policy_hold_shadow_pairs,174);
assert.equal(e.summary.taxonomy_review_products,0);
assert.equal(e.summary.live_product_market_pairs,0);
assert.equal(e.pairs.length,455);
assert(e.pairs.every(x=>x.shadow_eligible===true));
assert(e.pairs.every(x=>x.stylist_eligible===true));
assert(e.pairs.every(x=>x.live_eligible===false));
assert(e.pairs.every(x=>x.production_exposure===false));
assert(e.pairs.every(x=>x.market_shelf_key===x.country+"/"+x.department+"/"+x.category));
assert.deepEqual(Object.keys(e.departments).sort(),["kitchen","men","pets","tech","women"]);
assert.equal(e.departments.women["women-dresses"].length,6);
assert.equal(e.departments.pets["pet-accessories"].length,2);
assert.equal(e.departments.tech["electronics"].length,3);
assert.equal(e.departments.tech["computer-accessories"].length,1);
assert.equal(e.departments.tech["wearable-accessories"].length,1);
assert.equal(e.departments.men["men-tops"].length,1);
assert.equal(e.departments.kitchen["kitchen-tools"].length,1);
assert.equal(gate.version,"HUNT-COUNTRY-MARKET-GATE-V7");
assert.equal(gate.eprolo_state.global_product_market_shadow.live_product_market_pairs,0);
assert.equal(routing.current_state.taxonomy_review_products,0);
console.log("PASS boom-eprolo-global-product-market-shelf-v2");
