const fs=require("fs"),assert=require("assert");
const t=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-ACADEMY-TRAINING-SET-V3-IL-2026-09-22.json","utf8"));
const q=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-F35-VISUAL-QA-ROUND3-2026-09-22.json","utf8"));
const gap=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-MENS-FOOTWEAR-GAP-SCAN-2026-09-22.json","utf8"));
assert.equal(t.version,"HUNT-STYLIST-TRAINING-SET-V3-IL");
assert.equal(t.verified_products,37);
assert.equal(t.cj_il_verified_added,10);
assert.equal(t.production_effect,false);
const sneaker=t.products.find(x=>String(x.product_id)==="2609090656121615600");
assert(sneaker,"new verified sneaker missing");
assert.equal(sneaker.commercial_training_flag,"HIGH_SHIPPING_BURDEN");
assert.deepEqual(sneaker.verified_markets,["IL"]);
const live=gap.results.find(x=>x.item_id==="2609090656121615600");
assert.equal(live.status,"VERIFIED");
assert.equal(q.rework.look_id,"LOOK-05");
assert.equal(q.rework.new_footwear.product_id,"2609090656121615600");
assert.equal(q.rework.new_footwear.product_truth_il,"PASS");
assert.equal(q.rework.new_footwear.style_fit,"PASS_WITH_EDIT");
assert.equal(q.rework.new_footwear.commercial_fit,"WARNING_HIGH_SHIPPING");
assert.equal(q.counters.looks_can_continue,4);
assert.equal(q.counters.looks_rework,1);
assert.equal(q.counters.hero_ready,0);
assert.equal(q.mastery_change,false);
assert.equal(q.production_effect,false);
console.log("PASS boom-stylist-f35-round3");
