const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-stylist-academy-contract.json","utf8"));
assert.equal(c.version,"BOOM-STYLIST-ACADEMY-V2");
assert.equal(c.mode,"SHADOW_TRAINING");
assert.equal(c.production_influence,false);
assert.equal(c.autonomous_shelf_reorder,false);
assert.equal(c.publishing_authorized,false);
assert(c.tracks.some(x=>x.id==="S2"));
assert(c.tracks.some(x=>x.id==="M1"));
assert(c.exams.every(x=>x.pass_score===85));
assert(c.exams.some(x=>x.id==="DEPARTMENT-6-LAYER-SURVEY"));
assert(c.safety_and_trust.some(x=>x.includes("Do not critique")));
assert(c.mastery[c.mastery.length-1].requirement.includes("Owner Gate"));
assert.equal(c.preference_layers.length,6);
assert.equal(c.department_learning.length,17);
assert.equal(c.multidisciplinary_curriculum.length,10);
assert.equal(c.current_state.mastery_level,0);
assert.equal(c.current_state.completed_exams,0);
assert.equal(c.current_state.course_completion,"NOT_CLAIMED");
assert.equal(c.current_state.survey_layers,6);
assert.equal(c.current_state.departments_mapped,17);
assert(c.current_state.training_dataset.includes("36_VERIFIED_PRODUCTS_IL"));
assert.equal(c.current_state.assortment_gate_il,"PASS_4_FOOTWEAR_6_BOTTOMS");
assert.equal(c.current_state.style_round2,"READY_FOR_VISUAL_QA");
assert.equal(c.current_state.product_truth_round2,"PASS_IL");
assert(c.brand_case_study_policy.blocked.includes("Do not copy"));
const html=fs.readFileSync("boom-brain-studio.html","utf8");
const js=fs.readFileSync("boom-brain-studio.js","utf8");
assert(html.includes('id="bs-stylist-academy"'));
assert(js.includes("async function renderStylistAcademy()"));
assert(js.includes("HUNT-STYLIST-ACADEMY-TRAINING-SET-V2-IL-2026-09-22.json"));
assert(js.includes("HUNT-STYLIST-F35-ROUND2-2026-09-22.json"));
assert(js.includes("subjective score false"));
console.log("PASS boom-stylist-academy-v2");
