const assert=require("node:assert");
const R=require("./boom-f50-current-research.js").RECEIPT;
assert.strictEqual(R.protocol_token,"F50-DEEP-HUNT-CONTINUE");
assert.strictEqual(R.saved_candidate_id,"HUNT_PROMISE_MESH");
assert.strictEqual(R.saved_candidate_status,"KILLED_THIS_ROUND_REOPENABLE_WITH_NEW_EVIDENCE");
assert.strictEqual(R.mechanism_fingerprint,"f50_0e5bbbb820831132");
assert.strictEqual(R.formal_evidence_imported,true);
assert.strictEqual(R.prior_art_attack_state,"HOLD");
assert.strictEqual(R.patents_verified,6);
assert.strictEqual(R.prior_art_surfaces_complete,false);
assert.strictEqual(R.economics_state,"HOLD");
assert.strictEqual(R.red_team_state,"HOLD");
assert.strictEqual(R.research_memory_state,"READY");
assert.strictEqual(R.winner_claim_allowed,false);
assert.strictEqual(R.current_final_result,"ZERO");
assert.strictEqual(R.reopen_requires_new_evidence,true);
assert.strictEqual(R.payments_live,false);
assert.strictEqual(R.paid_spend,false);
assert.strictEqual(R.external_publish,false);
assert.strictEqual(R.execute_actions,false);
console.log("boom_f50_current_research=PASS");