const fs=require("fs"),assert=require("assert");
const map=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-CURRENT-LOOK-VISUAL-MAP-2026-09-22.json","utf8"));
const pf=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-PRINTFUL-CATALOG-VISUAL-MAP-2026-09-22.json","utf8"));
const cj=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-CURRENT-LOOKS-CJ-VISUAL-META-2026-09-22.json","utf8"));
const qa=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-TWO-THEME-LOOK-BOARD-QA-2026-09-22.json","utf8"));
const academy=JSON.parse(fs.readFileSync("boom-stylist-academy-contract.json","utf8"));
const lighting=JSON.parse(fs.readFileSync("boom-hunt-cinematic-lighting-contract.json","utf8"));
const html=fs.readFileSync("boom-stylist-shadow-look-board.html","utf8");
assert.equal(map.production_effect,false);
assert.equal(map.looks.length,5);
const items=map.looks.flatMap(x=>x.items);
assert.equal(items.length,25);
assert(items.every(x=>x.visual&&x.visual.image_url),"all look tiles need an image");
assert.equal(pf.items.length,14);
assert(pf.items.every(x=>x.image_scope==="OFFICIAL_PRINTFUL_CATALOG_BASE_IMAGE"));
assert.equal(cj.items.length,9);
assert(cj.items.every(x=>x.image_scope==="EXACT_VARIANT"));
assert.equal(qa.production_effect,false);
assert.equal(qa.themes.light.result,"PASS_DISPLAY");
assert.equal(qa.themes.dark.result,"PASS_DISPLAY");
assert.equal(qa.gate_state.silhouette_display_qa,"PASS_BOTH_THEMES");
assert.equal(qa.gate_state.exact_printful_artwork_qa,"PENDING");
assert.equal(qa.gate_state.commercial_hero_gate,"BLOCKED");
assert.equal(qa.gate_state.mastery_change,false);
assert.equal(academy.current_state.two_theme_look_board,"PASS_BOTH_THEMES_BASE_IMAGES_ONLY");
assert.equal(academy.current_state.exact_printful_artwork,"PENDING");
assert.equal(academy.current_state.hero_ready,0);
assert.equal(academy.current_state.mastery_level,0);
assert.equal(lighting.qa.two_theme_look_board,"PASS_BOTH_THEMES");
assert.equal(lighting.qa.final_printful_artwork,"PENDING");
assert(html.includes("BOOM STYLIST · SHADOW VISUAL QA"));
assert(html.includes("LIGHT · OFF-WHITE"));
assert(html.includes("DARK · SAPPHIRE / GRAPHITE"));
assert(html.includes("PRINTFUL BASE IMAGE"));
assert(html.includes("EXACT VARIANT"));
console.log("PASS boom-stylist-two-theme-look-board");
