const fs=require("fs"),assert=require("assert");
const e=JSON.parse(fs.readFileSync("evidence/HUNT-EPROLO-GLOBAL-PRODUCT-MARKET-SHELF-2026-09-23.json","utf8"));
const gate=JSON.parse(fs.readFileSync("boom-country-market-gate-contract.json","utf8"));
assert.equal(e.version,"HUNT-EPROLO-GLOBAL-PRODUCT-MARKET-SHELF-V1");
assert.equal(e.production_effect,false);
assert.equal(e.summary.products,4);
assert(e.summary.countries_represented>=20);
assert(e.summary.shipping_shadow_product_market_pairs>0);
assert.equal(e.summary.policy_mapped_shadow_pairs+e.summary.policy_hold_shadow_pairs,e.summary.shipping_shadow_product_market_pairs);
assert.equal(e.summary.live_product_market_pairs,0);
assert(e.pairs.every(x=>x.shadow_eligible===true));
assert(e.pairs.every(x=>x.live_eligible===false));
const men=e.products.find(x=>x.product_id==="24539904");
assert(men.shipping_shadow_markets.includes("DE"));
assert(men.shipping_shadow_markets.includes("US"));
assert(!men.shipping_shadow_markets.includes("IL"));
const women=e.products.find(x=>x.product_id==="19374567");
assert(women.shipping_shadow_markets.includes("IL"));
const tech=e.products.find(x=>x.product_id==="26921252");
assert(tech.shipping_shadow_markets.includes("IL"));
assert.equal(gate.version,"HUNT-COUNTRY-MARKET-GATE-V5");
assert.equal(gate.eprolo_state.global_product_market_shadow.live_product_market_pairs,0);
console.log("PASS boom-eprolo-global-product-market-shelf");
