const assert=require("node:assert/strict");
const fs=require("node:fs");
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const s7=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE7-FINAL-PREVIEW-2026-09-23.json");
const q=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-QA-SHORTLIST-V2-2026-09-23.json");
const ship=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-SHIPPING-VERIFY-2026-09-23.json");
const gate=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-MEDIA-PROFIT-GATE-2026-09-23.json");
const sel=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-SELECTION-2026-09-23.json");
const prev=read("evidence/HUNT-PRODUCT-PLACEMENT-STAGE8-P0-PREVIEW-2026-09-23.json");
for(const x of [q,ship,gate,sel,prev])assert.equal(x.production_effect,false);
assert.equal(ship.summary.final_net_profit_verified_products,0);
assert.equal(gate.summary.final_net_profit_verified_products,0);
assert.equal(sel.summary.final_net_profit_verified_products,0);
assert.equal(prev.summary.final_net_profit_verified_products,0);
assert.equal(sel.summary.selected_products,sel.selected.length);
assert.equal(prev.summary.stage8_selected_products,sel.selected.length);
assert.equal(prev.summary.canonical_products,s7.summary.canonical_products+sel.selected.length);
assert(sel.selected.every(x=>x.stage8_gate==="PASS"));
assert(sel.selected.every(x=>x.shipping_status==="VERIFIED_4_OF_4"));
assert(sel.selected.every(x=>x.media_technical.state==="PASS"));
assert(sel.selected.every(x=>x.profit_gate_v21_pass===true));
assert(prev.summary.rails_empty < s7.summary.rails_empty);
console.log("Product Placement Stage8 Supplier Recovery: PASS");
