const fs=require("fs"),vm=require("vm"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-performance-mobile-readiness-contract.json","utf8"));
assert.equal(c.authority,"NONE");
assert.equal(c.current_truth.mobile_390.dom_nodes,2899);
assert(c.hard_rules.some(x=>/Never call local timing data/.test(x)));
const src=fs.readFileSync("boom-performance-mobile-readiness.js","utf8");
const ctx={window:{}};vm.createContext(ctx);vm.runInContext(src,ctx);
const P=ctx.window.BoomPerformanceMobileReadiness;
let r=P.evaluate({mobile_390:c.current_truth.mobile_390,tablet_768:c.current_truth.tablet_768,desktop_1280:c.current_truth.desktop_1280,desktop_1440:c.current_truth.desktop_1440,pwa_preview_proof:false,budgets:c.budgets});
assert.equal(r.mobile.state,"PASS_LOCAL");
assert.equal(r.tablet.state,"PASS_LOCAL");
assert.equal(r.desktop1280.state,"PASS_LOCAL");
assert.equal(r.desktop1440.state,"PASS_LOCAL");
assert.equal(r.state,"LOCAL_RESPONSIVE_PASS_PREVIEW_PWA_PROOF_PENDING");
r=P.evaluate({mobile_390:{...c.current_truth.mobile_390,dom_nodes:9000},tablet_768:c.current_truth.tablet_768,desktop_1280:c.current_truth.desktop_1280,desktop_1440:c.current_truth.desktop_1440,pwa_preview_proof:true,budgets:c.budgets});
assert.equal(r.state,"BLOCKED_LOCAL_QA");
const home=fs.readFileSync("hunt-deal.js","utf8");
assert(home.includes("initialShelfMountLimit"));
assert(home.includes("hunt:shelf-batch-mounted"));
assert(home.includes('rootMargin:"1200px 0px"'));
const css=fs.readFileSync("hunt-shop.css","utf8");
assert(css.includes("BOOM mobile touch-target hardening"));
assert(css.includes("#hd-shopping-survey-skip{width:44px!important;height:44px!important}"));
const sw=fs.readFileSync("service-worker.js","utf8");
assert(sw.includes('const CACHE="hunt-shell-pwa2"'));
assert(/js\|css\|json\|webmanifest/.test(sw));
assert(sw.includes("networkFirst(request)"));
const pwa=fs.readFileSync("pwa.js","utf8");
assert(pwa.includes('service-worker.js?v=pwa2'));
assert(pwa.includes('updateViaCache:"none"'));
const index=fs.readFileSync("index.html","utf8");
assert(index.includes("hunt-deal.js?v=perf2"));
assert(index.includes("hunt-shop.css?v=perf2"));
console.log("BOOM Performance/Mobile Readiness: PASS — bounded initial DOM, mobile touch targets and PWA code-cache hardening enforced");