const fs=require("fs"),assert=require("assert");
const json=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const brains=json("boom-brain-registry.json");
const agents=json("boom-agent-registry.json");
const skills=json("boom-skill-registry.json");
const tools=json("boom-tool-registry.json");
const gates=json("boom-owner-gate-map.json");
const auto=json("boom-automation-control-plane.json");
const dept=json("boom-shelf-department-contract.json");
const ready=json("boom-control-plane-readiness.json");
const actions=json("boom-action-contract.json");
const inv=json("boom-interaction-inventory.json");
const scheduler=json("boom-scheduler-contract.json");

assert.equal(brains.primary_brains.length,8,"exactly 8 Primary Brains");
assert.equal(new Set(brains.primary_brains.map(x=>x.id)).size,8,"brain IDs unique");
assert.equal(agents.legacy_manager_map.length,31,"all 31 legacy managers mapped");
assert.equal(agents.department_policy.representation,"TAXONOMY_MODULES_NOT_AGENTS");
assert.equal(skills.skills.length,24,"all current skill files classified");
assert(tools.runtime_tools.every(x=>x.authority==="NONE"),"tools cannot own decisions");
assert.equal(auto.workflows.length,6,"six canonical HUNT workflows");
assert.equal(auto.adapters.find(x=>x.id==="n8n_adapter").authority,"NONE");
assert.equal(auto.adapters.find(x=>x.id==="n8n_adapter").status,"CODED_NOT_DEPLOYED_NOT_CONNECTED");
assert.equal(dept.departments.length,17);
assert.equal(dept.departments.filter(x=>x.status==="VERIFIED_SOURCE").length,17);
assert.equal(dept.departments.filter(x=>x.status==="UNRESOLVED").length,0);
assert.equal(ready.overall,"NOT_READY_FOR_ACTIVATION");
assert.equal(ready.production_changed,false);
assert.equal(ready.n8n_connected,false);
assert.equal(ready.new_edge_functions_deployed,false);
assert(gates.actions.every(x=>x.gate==="REQUIRED"));
assert.equal(scheduler.owner,"boom_orchestrator");
const known=new Set(actions.actions.map(x=>x.action_id));
for(const row of inv.interactions)assert(known.has(row.action_id),"unknown inventory action "+row.action_id);
const ownerMappings=inv.interactions.filter(x=>x.action_id==="boom.owner_gate.decide");
assert.equal(ownerMappings.length,2);
console.log("BOOM CONTROL PLANE INTEGRITY: PASS — ownership, automation, truth, gates and readiness are coherent");