const fs=require("fs"),assert=require("assert");
const t=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-ACADEMY-TRAINING-SET-V4-IL-2026-09-22.json","utf8"));
const q=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-F35-VISUAL-QA-ROUND4-2026-09-22.json","utf8"));
const scan=JSON.parse(fs.readFileSync("evidence/HUNT-STYLIST-LOOK01-FOOTWEAR-SCAN-2026-09-22.json","utf8"));
assert.equal(t.version,"HUNT-STYLIST-TRAINING-SET-V4-IL");
assert.equal(t.verified_products,40);
assert.equal(t.cj_il_verified_added,13);
assert.equal(t.production_effect,false);
const shoe=t.products.find(x=>String(x.product_id)==="2609070619011621100");
assert(shoe,"LOOK-01 replacement missing");
assert.equal(shoe.color,"Light Gray");
assert.equal(shoe.variant_id,"2609070619011621900");
assert.equal(shoe.commercial_training_flag,"HIGH_SHIPPING_BURDEN");
assert.deepEqual(shoe.verified_markets,["IL"]);
const live=scan.results.find(x=>x.item_id==="2609070619011621100");
assert.equal(live.status,"VERIFIED");
assert.equal(q.look01_rework.new_footwear.product_id,"2609070619011621100");
assert.equal(q.look01_rework.new_footwear.exact_variant_color,"Light Gray");
assert.equal(q.look01_rework.exact_bottom.exact_variant_color,"Beige");
assert.equal(q.look01_rework.new_footwear.product_truth_il,"PASS");
assert.equal(q.look01_rework.new_footwear.style_fit,"PASS_WITH_EDIT");
assert.equal(q.look01_rework.new_footwear.commercial_fit,"WARNING_HIGH_SHIPPING");
assert.equal(q.counters.looks_can_continue,5);
assert.equal(q.counters.looks_rework,0);
assert.equal(q.counters.hero_ready,0);
assert.equal(q.mastery_change,false);
assert.equal(q.production_effect,false);
console.log("PASS boom-stylist-f35-round4");
