const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-hunt-taxonomy-stylist-routing-contract.json","utf8"));
const e=JSON.parse(fs.readFileSync("evidence/HUNT-GLOBAL-TAXONOMY-STYLIST-ROUTING-2026-09-23.json","utf8"));
assert.equal(c.version,"HUNT-TAXONOMY-STYLIST-ROUTING-V1");
assert.equal(c.mode,"SHADOW_ONLY");
assert.equal(c.production_effect,false);
assert.equal(c.current_state.canonical_departments,17);
assert.equal(c.current_state.truth_products_routed,15);
assert.equal(c.current_state.countries_in_global_matrix,33);
assert.equal(c.current_state.shipping_shadow_product_market_pairs,455);
assert.equal(c.current_state.taxonomy_review_products,0);
assert.equal(c.current_state.production_authority,false);
assert.equal(e.summary.products,15);
assert.equal(e.summary.departments_represented,5);
assert.equal(e.summary.canonical_category_shelves_represented,7);
assert.equal(e.summary.taxonomy_review_products,0);
assert.equal(e.summary.live_products,0);
const by=Object.fromEntries(e.products.map(x=>[x.product_id,x]));
assert.equal(by["19374567"].department,"women");
assert.equal(by["19374567"].canonical_category,"women-dresses");
assert.equal(by["24539904"].canonical_category,"men-tops");
assert.equal(by["26556212"].canonical_category,"kitchen-tools");
assert.equal(by["26972478"].canonical_category,"electronics");
assert.equal(by["26921252"].canonical_category,"computer-accessories");
assert(e.products.every(x=>x.live_eligible===false));
assert(e.products.every(x=>x.production_exposure===false));
assert(e.products.every(x=>x.stylist_input==="ELIGIBLE_FOR_SHADOW_ARRANGEMENT"));
console.log("PASS boom-hunt-taxonomy-stylist-routing");
