const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-hypersku-gap-fill-profit-contract.json","utf8"));
const e=JSON.parse(fs.readFileSync("evidence/HUNT-HYPERSKU-GAP-FILL-PROFIT-SHADOW-2026-09-23.json","utf8"));
assert.equal(c.version,"HUNT-HYPERSKU-GAP-FILL-PROFIT-SHADOW-V2");
assert.equal(c.mode,"CURATION_AND_QUOTE_GATE");
assert.equal(c.production_effect,false);
assert.equal(c.provider,"HyperSKU");
assert.equal(c.provider_state.local_curated_targets,71);
assert.equal(c.provider_state.open_api_bulk_pull,false);
assert.equal(c.provider_state.live_checkout,false);
assert.equal(c.provider_state.fulfillment,false);
assert.equal(c.shelf_gap_state.zero_canonical_categories,38);
assert.equal(c.shelf_gap_state.thin_under_12_categories,26);
assert.equal(c.shelf_gap_state.post_cj_verified_products,39);
assert.equal(c.shelf_gap_state.post_cj_category_rails,132);
assert.equal(c.shelf_gap_state.post_cj_total_browsable_products,5182);
assert.equal(c.shelf_gap_state.post_cj_remaining_zero_categories,1);
assert.deepEqual(c.shelf_gap_state.post_cj_zero_categories.map(x=>x.department+"/"+x.category).sort(),["home/entryway"]);
assert.equal(c.hypersku_priority_1_sourcing_queue.length,1);
assert.equal(c.hypersku_priority_1_sourcing_queue[0].department+"/"+c.hypersku_priority_1_sourcing_queue[0].category,"home/entryway");
assert(c.hypersku_priority_1_sourcing_queue.every(x=>x.status==="SMART_SOURCING_REQUIRED"));
assert.equal(c.public_profit_benchmarks.length,12);
assert(c.public_profit_benchmarks.every(x=>x.final_profit_verified===false));
assert(c.public_profit_benchmarks.every(x=>x.shipping_quote_required===true));
assert.equal(c.exact_private_product_701425.product_cost_usd,5.54);
assert.equal(c.exact_private_product_701425.hunt_price_gate_shadow_usd,10.99);
assert.equal(c.exact_private_product_701425.final_profit_verified,false);
assert.equal(e.summary.curated_targets,71);
assert.equal(e.summary.final_profit_verified_products,0);
console.log("PASS boom-hypersku-gap-fill-profit-shadow");
