const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-supplier-product-intake-contract.json","utf8"));
assert.equal(c.brain,"commerce_truth_brain");
assert.equal(c.source_of_truth.partner_candidate.access,"SERVER_ONLY_RLS");
assert.equal(c.boundaries.supplier_order,false);
assert.equal(c.boundaries.invented_stock,false);
assert(c.stages.includes("unit_economics"));
assert(c.stages.includes("placement_decision"));
assert(c.stages.includes("overlap_resolution"));
assert(c.stages.indexOf("overlap_resolution")<c.stages.indexOf("placement_decision"));
assert(c.stages.indexOf("placement_decision")<c.stages.indexOf("shelf_candidate"));
assert(c.pass_requirements.includes("placement_decision = PASS"));
assert.deepEqual(c.output.placement_block_states,["REVIEW","REJECT","UNKNOWN"]);
assert(c.pass_requirements.some(x=>/profit gate/i.test(x)));
console.log("Supplier intake contract: PASS — truth gates, existing stores, no order/publish");