const assert=require("node:assert/strict");
const g=require("./boom-product-placement-overlap-gate.js");
const e=(rail,title,cid)=>g.evaluate({current_rail:rail,title,supplier_category_id:cid});
let r=e("gifts/gift-decor","Alloy double-layer star line ring",33);
assert.equal(r.state,"SAFE_MOVE_CANDIDATE");assert.equal(r.target_rail,"accessories/jewelry-rings");
r=e("gifts/gift-decor","Self-defense ring outdoor safety tool",33);
assert.equal(r.state,"HOLD_OUT_OF_SCOPE");
r=e("kitchen/drinkware","Heat resistant coffee mug with handle",127);
assert.equal(r.state,"KEEP");
r=e("electrical/electrical-lighting","22.5W magnetic power bank fast charging",38);
assert.equal(r.target_rail,"tech/power-banks");
r=e("electrical/electrical-lighting","Wireless charger desk lamp clock 6 in 1",41);
assert.equal(r.state,"REVIEW");
r=e("beauty/beauty-tools","Scalp care hair growth serum",90);
assert.equal(r.target_rail,"beauty/hair");
r=e("beauty/beauty-tools","Dental whitening tray",93);
assert.equal(r.state,"REVIEW");
r=e("sports/fitness","Knee brace support for running and cycling",73);
assert.equal(r.state,"REVIEW");assert.equal(r.target_rail,"sports/fitness-accessories");
r=e("sports/fitness","Running waist bag for gym",70);
assert.equal(r.target_rail,"sports/sports-bags");
r=e("pets/pet-accessories","Warm knitted dog clothes",1214);
assert.equal(r.target_rail,"pets/pet-clothing");
console.log("Product Placement Stage6 Overlap Gate: PASS");
