const fs=require("fs"),assert=require("assert");
const e=JSON.parse(fs.readFileSync("evidence/HUNT-EPROLO-GLOBAL-COUNTRY-ENGINE-2026-09-23.json","utf8"));
const gate=JSON.parse(fs.readFileSync("boom-country-market-gate-contract.json","utf8"));

assert.equal(e.version,"HUNT-EPROLO-GLOBAL-COUNTRY-ENGINE-V4");
assert.equal(e.mode,"GLOBAL_SHADOW");
assert.equal(e.provider,"EPROLO");
assert.equal(e.production_effect,false);
assert.equal(e.country_key,"ISO_3166_1_ALPHA2");
assert.equal(e.summary.markets_checked,33);
assert.equal(e.summary.markets_with_at_least_one_shipping_pass,33);
assert.equal(e.summary.mapped_policy_markets,19);
assert.equal(e.summary.unmapped_policy_hold_markets,14);
assert.equal(e.summary.global_truth_products_checked,15);
assert.equal(e.summary.live_eligible_products,0);
assert.equal(e.global_product_market_shadow.products,15);
assert.equal(e.global_product_market_shadow.countries_represented,33);
assert.equal(e.global_product_market_shadow.possible_product_market_pairs,495);
assert.equal(e.global_product_market_shadow.shipping_shadow_product_market_pairs,455);
assert.equal(e.global_product_market_shadow.policy_mapped_shadow_pairs,281);
assert.equal(e.global_product_market_shadow.policy_hold_shadow_pairs,174);
assert.equal(e.global_product_market_shadow.full_33_market_matrix,true);
assert.equal(e.global_product_market_shadow.live_product_market_pairs,0);
const by=Object.fromEntries(e.markets.map(x=>[x.country,x]));
assert.equal(by.IL.shipping_pass_count,13);
assert.equal(by.DE.shipping_pass_count,15);
assert.equal(by.US.shipping_pass_count,15);
assert.equal(by.SG.shipping_pass_count,15);
assert.equal(by.SA.shipping_pass_count,2);
assert.equal(by.BR.shipping_pass_count,3);
assert.equal(by.HK.shipping_pass_count,11);
assert.equal(by.CA.market_policy_state,"HOLD_UNMAPPED");
assert.equal(by.DE.market_policy_state,"REVIEW_REQUIRED");
assert.equal(new Set(e.markets.map(x=>x.country)).size,33);
assert(e.markets.every(x=>x.sample_products===15));
assert(e.markets.every(x=>x.real_money_live===false));
assert.equal(gate.version,"HUNT-COUNTRY-MARKET-GATE-V7");
assert.equal(gate.eprolo_state.global_live_eligible_products,0);
assert.equal(gate.eprolo_state.persisted_catalog_discovery_enabled,false);
console.log("PASS boom-eprolo-global-country-engine-v4");
