const fs=require("fs"),assert=require("assert");
const c=JSON.parse(fs.readFileSync("boom-printful-fulfillment-readiness-contract.json","utf8"));
const r=fs.readFileSync("boom-printful-fulfillment-readiness.mjs","utf8");
const d=fs.readFileSync("boom-printful-draft-test.mjs","utf8");
assert.equal(c.mode,"DRAFT_TEST_ONLY");
assert.equal(c.production_checkout,false);
assert.equal(c.live_fulfillment,false);
assert(c.token_policy.required_scopes.includes("orders"));
assert(r.includes('get("/oauth/scopes")'));
assert(r.includes('get("/orders?limit=1")'));
assert.equal((r.match(/method:"POST"/g)||[]).length,0);
assert(d.includes('process.argv.includes("--create-draft")'));
assert(d.includes('PRINTFUL_ALLOW_DRAFT_CREATE'));
assert(d.includes('https://api.printful.com/v2/orders'));
assert(!d.includes('/confirm'));
assert(!d.includes("confirm=true"));
assert(!d.includes('method:"DELETE"'));
assert(!d.includes('method:"PUT"'));
console.log("PASS boom-printful-fulfillment-readiness");