const assert=require("node:assert");
const fs=require("node:fs");
global.window={};
require("./brand-video-router.js");
require("./brand-creative-qa.js");
const dispatch=require("./brand-video-dispatch.js");
const mission=JSON.parse(fs.readFileSync("brand-factory-seed-il-0001.json","utf8"));
const plan=window.BoomVideoRouter.buildPlan(mission,{productImageUrl:mission.product_truth_snapshot.image_url,ownerApproved:false});
const qa=window.BoomCreativeQA.tournament(plan,mission,{limit:4,minScore:62});
const truth={source_verified:true,provider:"CJdropshipping",item_id:mission.product_truth_snapshot.item_id,variant_id:mission.product_truth_snapshot.variant_id,country_code:"IL",verification:{verified_at:"2026-09-17T19:44:55.928Z"}};
const req=dispatch.buildDryRunRequest(qa,plan,truth);
assert.equal(req.mode,"dry_run");
assert.equal(req.route_plan.execution_allowed,false);
assert.equal(req.route_plan.shots.length,4);
assert(req.route_plan.shots.every(s=>s.aspect_ratio==="9:16"));
assert(req.route_plan.shots.every(s=>s.mode==="image-to-video"));
assert.equal(dispatch.alias("google-veo31"),"veo-3.1");
assert.throws(()=>dispatch.buildDryRunRequest(qa,plan,{source_verified:false}),/PRODUCT_TRUTH_REVERIFY_REQUIRED/);
console.log("brand_video_dispatch_tests=PASS");
