const assert=require("node:assert");
const fs=require("node:fs");
const vm=require("node:vm");
const qa=require("./brand-creative-qa.js");
const seed=require("./brand-factory-seed-il-0001.json");
const src=fs.readFileSync("brand-video-router.js","utf8");
const ctx={window:{},globalThis:{}};vm.createContext(ctx);vm.runInContext(src,ctx);
const router=ctx.window.BoomVideoRouter;
const plan=router.buildPlan(seed,{productImageUrl:"https://example.test/verified-product.jpg",ownerApproved:false});
const result=qa.tournament(plan,seed,{limit:4});
assert.equal(plan.shot_count,12,"expected 12 routed shots");
assert.equal(result.status,"QA_SHORTLIST");
assert.equal(result.execution_allowed,false);
assert(result.finalist_count>=3&&result.finalist_count<=4,"expected 3-4 finalists");
assert(result.generation_reduction_pct>=66,"expected at least two thirds reduction");
assert(new Set(result.finalists.map(x=>x.script)).size>=3,"shortlist should preserve script diversity");
assert(result.finalists.every(x=>x.scores.claim_safety>=70&&!x.blocked),"unsafe shot selected");
const unsafe=qa.scoreShot({id:"X-1",script:"bad",visual:"phone",overlay:"Military-grade shockproof guarantee",reference_image:"x"});
assert.equal(unsafe.blocked,true,"risky claim should be blocked");
assert(result.blockers.includes("OWNER_APPROVAL_REQUIRED_BEFORE_GENERATION"));
console.log("brand_creative_qa_tests=PASS");
console.log(JSON.stringify({input:result.input_shots,finalists:result.finalists.map(x=>({id:x.id,script:x.script,score:x.scores.overall})),reduction:result.generation_reduction_pct},null,2));
