const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('hunt-home-3.js','utf8');
const css=fs.readFileSync('hunt-home-3.css','utf8');
const building=fs.readFileSync('hunt-building.css','utf8');
const guard=fs.readFileSync('hunt-building-guard.js','utf8');
const deal=fs.readFileSync('hunt-deal.js','utf8');
const theme=fs.readFileSync('hunt-theme.js','utf8');

assert(html.includes('hd-home3'),'Home 3 body contract missing');
assert(html.includes('hunt-home-3.css?v=2'),'Home 3 stylesheet missing');
assert(html.includes('hunt-building.css?v=3'),'Building stylesheet missing');
assert(html.includes('hunt-home-3.js?v=4'),'Home 3 runtime missing');
assert(html.includes('hunt-building-guard.js?v=3'),'Visual Order Guard runtime missing');
assert(html.includes('hunt-deal.js?v=boomet6'),'Controlled Market Hall runtime missing');
assert(!html.includes('class="hd-advisor glass"'),'Legacy HUNT Advisor must be removed from Home hero');
assert(!html.includes('hunt-wow.js?v=dynamic2'),'Legacy Home renderer must not run on Home 3');
assert(html.includes('id="hunt-hero4"'),'Hero 4 must replace the retired Home 3 mosaic');
assert(html.includes('id="hd-home3-women"'),'Women edit missing');
assert(html.includes('id="hd-home3-accessories"'),'Accessories world missing');
assert(html.includes('id="hd-home3-beauty"'),'Beauty world missing');
assert(html.includes('id="hd-home3-for-you"'),'For You world missing');
assert(html.includes('id="hd-home3-look-products"'),'Deal Builder entry missing');
assert(html.includes('id="hd-home3-fresh"'),'Fresh catalog world missing');
assert(html.includes('id="hd-home-random-grid"'),'Endless discovery engine missing');
assert(js.includes('retail_price_verified === true'),'Home cards must not invent retail price');
assert(js.includes('profit_gate_status'),'Home retail display must respect Profit Gate');
assert(js.includes('H.isNewArrival?.(item)'),'New badge must use timestamp evidence');
assert(js.includes('H.signals?.()'),'For You must use real interaction signals');
assert(js.includes('window.addEventListener("hunt:shelves"'),'Home 3 must render from connected catalog event');
for(const token of ['hunt-men-floor','hunt-kids-floor','hunt-beauty-floor','hunt-tech-floor','hunt-home-floor','hunt-active-floor','hunt-fresh-floor','hunt-market-hall','hunt-advertising-floor','hunt-ai-floor','hunt-ai-media-floor','hunt-penthouse']) assert(js.includes(token),'Building floor missing: '+token);
assert(js.includes('balancedDepartmentMix'),'Homepage category balance guard missing');
assert(!js.includes('departments.after(personal)'),'Personalization must not reorder building floors');
assert(js.includes('applyBuildingOrder()'),'Stable building ordering missing');
assert(js.includes('btn.contains(e.target)'),'Categories menu outside-click guard missing');
assert(html.includes('data-open-categories'),'Header/mobile Categories trigger missing');
assert(deal.includes('homeFeedBatchSize')&&deal.includes('homeFeedCursor+batchSize'),'Market Hall must use responsive controlled batches');
assert(deal.includes('max-width:760px')&&deal.includes('?8:12'),'Market Hall must use 8 mobile / 12 desktop batches');
assert(!deal.includes('homeFeedCursor+48'),'Legacy 48-product batch must stay removed');
assert(deal.includes('balanceHomeFeed(ranked)'),'Market Hall category balance guard missing');
assert(!deal.includes('new IntersectionObserver(entries=>'),'Home Market Hall must not auto-expand while scrolling');
assert(deal.includes('if(title)title.textContent'),'Legacy advisor writes must be null-safe');
assert(theme.includes('classList.contains("hd-home3")'),'Legacy Home theme renderer must stand down on Home 3');
assert(css.includes('HUNT HOME 3.0 · STRUCTURAL REDESIGN'),'Home 3 visual contract missing');
assert(css.includes('@media(max-width:760px)'),'Home 3 mobile contract missing');
assert(building.includes('.hd-building-floor-nav'),'Building floor navigation styling missing');
assert(building.includes('.hd-building-penthouse'),'Penthouse styling missing');
assert(building.includes('.hd-building-ai-media'),'AI media floor styling missing');
for(const token of ['FLOOR_ORDER','containmentState','duplicateIds','balanceState','horizontal_overflow','category_navigation','category_triggers','maxFloorHeight','huge_floors','hunt:visual-order-audit']) assert(guard.includes(token),'Visual Order Guard contract missing: '+token);
console.log('hunt_home3=PASS');
