const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('hunt-home-3.js','utf8');
const css=fs.readFileSync('hunt-home-3.css','utf8');
const deal=fs.readFileSync('hunt-deal.js','utf8');
const theme=fs.readFileSync('hunt-theme.js','utf8');

assert(html.includes('hd-home3'),'Home 3 body contract missing');
assert(html.includes('hunt-home-3.css?v=1'),'Home 3 stylesheet missing');
assert(html.includes('hunt-home-3.js?v=1'),'Home 3 runtime missing');
assert(!html.includes('class="hd-advisor glass"'),'Legacy HUNT Advisor must be removed from Home hero');
assert(!html.includes('hunt-wow.js?v=dynamic2'),'Legacy Home renderer must not run on Home 3');
assert(html.includes('id="hd-home3-hero-mosaic"'),'Editorial hero mosaic missing');
assert(html.includes('id="hd-home3-women"'),'Women edit missing');
assert(html.includes('id="hd-home3-accessories"'),'Accessories world missing');
assert(html.includes('id="hd-home3-beauty"'),'Beauty world missing');
assert(html.includes('id="hd-home3-for-you"'),'For You world missing');
assert(html.includes('id="hd-home3-look-products"'),'Deal Builder entry missing');
assert(html.includes('id="hd-home3-fresh"'),'Fresh catalog world missing');
assert(html.includes('id="hd-home-random-grid"'),'Endless discovery engine missing');
assert(js.includes('retail_price_verified === true'),'Home cards must not invent retail price');
assert(js.includes('profit_gate_status'),'Home retail display must respect Profit Gate');
assert(js.includes('H.isNewArrival?.(item)'),'New badge must use timestamp evidence');
assert(js.includes('H.signals?.()'),'For You must use real interaction signals');
assert(js.includes('window.addEventListener("hunt:shelves"'),'Home 3 must render from connected catalog event');
assert(deal.includes('if(title)title.textContent'),'Legacy advisor writes must be null-safe');
assert(theme.includes('classList.contains("hd-home3")'),'Legacy Home theme renderer must stand down on Home 3');
assert(css.includes('HUNT HOME 3.0 · STRUCTURAL REDESIGN'),'Home 3 visual contract missing');
assert(css.includes('@media(max-width:760px)'),'Home 3 mobile contract missing');
console.log('hunt_home3=PASS');
