import {MAX_INGEST_BYTES,VAULT_BUCKET,assertTransition,decisionNote,ownerDecision,planVaultAsset,postGenerationQA,previewTTL,validateTaskId} from "./vault-core.mjs";
import {buildVisualQAPlan,evaluateVisualQA} from "./visual-qa-core.mjs";
import {DEFAULT_VISION_MODEL,buildOpenAIVisionRequest,parseOpenAIVisionResponse} from "./vision-adapter-core.mjs";
const BASE=Deno.env.get("SUPABASE_URL")||"",SERVICE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const RUNWAY_SECRET=Deno.env.get("RUNWAYML_API_SECRET")||"",RUNWAY_TASK_URL="https://api.dev.runwayml.com/v1/tasks/",RUNWAY_VERSION="2024-11-06";
const OPENAI_VISION_ENABLED=Deno.env.get("BOOM_OPENAI_VISION_ENABLED")==="true",OPENAI_KEY=Deno.env.get("OPENAI_API_KEY")||"",OPENAI_VISION_MODEL=Deno.env.get("BOOM_OPENAI_VISION_MODEL")||DEFAULT_VISION_MODEL;
function cors(req:Request){const o=req.headers.get("origin")||"";const ok=o==="https://deep-hunt-market.netlify.app"||/^https:\/\/[a-z0-9-]+--deep-hunt-market\.netlify\.app$/i.test(o)||o==="http://localhost:18977"||o==="http://127.0.0.1:18977";return {"Access-Control-Allow-Origin":ok?o:"https://deep-hunt-market.netlify.app","Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function json(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":"no-store, private",...cors(req)}})}
function svc(extra:Record<string,string>={}){return {apikey:SERVICE,Authorization:"Bearer "+SERVICE,...extra}}
async function userFromReq(req:Request){const a=req.headers.get("authorization")||"";const t=a.startsWith("Bearer ")?a.slice(7).trim():"";if(!t)return null;const r=await fetch(BASE+"/auth/v1/user",{headers:{apikey:SERVICE,Authorization:"Bearer "+t},signal:AbortSignal.timeout(10000)});return r.ok?await r.json():null}
async function isAdmin(id:string){const r=await fetch(BASE+"/rest/v1/profiles?id=eq."+encodeURIComponent(id)+"&select=is_admin",{headers:svc(),signal:AbortSignal.timeout(10000)});if(!r.ok)return false;const d=await r.json();return d?.[0]?.is_admin===true}
function encodedPath(path:string){return path.split("/").map(encodeURIComponent).join("/")}
async function sha256Hex(bytes:ArrayBuffer){const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function existingAsset(mission:string,asset:string){const q=`?mission_id=eq.${encodeURIComponent(mission)}&creative_asset_id=eq.${encodeURIComponent(asset)}&select=*`;const r=await fetch(BASE+"/rest/v1/boom_media_assets"+q,{headers:svc(),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("VAULT_LEDGER_LOOKUP_FAILED");const d=await r.json();return d?.[0]||null}
async function runwayOutput(taskId:string){if(!RUNWAY_SECRET)throw new Error("RUNWAY_SECRET_REQUIRED");const r=await fetch(RUNWAY_TASK_URL+encodeURIComponent(taskId),{headers:{Authorization:"Bearer "+RUNWAY_SECRET,"X-Runway-Version":RUNWAY_VERSION},signal:AbortSignal.timeout(15000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("RUNWAY_STATUS_FAILED");if(String(d?.status||"")!=="SUCCEEDED")throw new Error("RUNWAY_TASK_NOT_SUCCEEDED");const first=Array.isArray(d?.output)?d.output[0]:null;const url=typeof first==="string"?first:String(first?.url||"");if(!url.startsWith("https://"))throw new Error("RUNWAY_OUTPUT_UNAVAILABLE");return url}
async function downloadVideo(url:string){const r=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(45000)});if(!r.ok)throw new Error("PROVIDER_MEDIA_DOWNLOAD_FAILED");const mime=(r.headers.get("content-type")||"").split(";")[0].trim().toLowerCase();if(!["video/mp4","video/webm"].includes(mime))throw new Error("PROVIDER_MEDIA_MIME_INVALID");const declared=Number(r.headers.get("content-length")||0);if(declared>MAX_INGEST_BYTES)throw new Error("PROVIDER_MEDIA_TOO_LARGE");const bytes=await r.arrayBuffer();if(!bytes.byteLength||bytes.byteLength>MAX_INGEST_BYTES)throw new Error("PROVIDER_MEDIA_TOO_LARGE");return {bytes,mime,size:bytes.byteLength,sha256:await sha256Hex(bytes)}}
async function uploadPrivate(path:string,media:{bytes:ArrayBuffer,mime:string}){const r=await fetch(`${BASE}/storage/v1/object/${VAULT_BUCKET}/${encodedPath(path)}`,{method:"POST",headers:svc({"content-type":media.mime,"x-upsert":"false","cache-control":"31536000"}),body:media.bytes,signal:AbortSignal.timeout(45000)});if(!r.ok){const e=await r.text().catch(()=>"");if(r.status===409)throw new Error("VAULT_OBJECT_ALREADY_EXISTS");throw new Error("VAULT_UPLOAD_FAILED"+(e?"_"+r.status:""))}}
async function deletePrivate(path:string){await fetch(`${BASE}/storage/v1/object/${VAULT_BUCKET}/${encodedPath(path)}`,{method:"DELETE",headers:svc(),signal:AbortSignal.timeout(10000)}).catch(()=>null)}
async function insertLedger(row:Record<string,unknown>){const r=await fetch(BASE+"/rest/v1/boom_media_assets",{method:"POST",headers:svc({"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify(row),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("VAULT_LEDGER_INSERT_FAILED");const d=await r.json();return d?.[0]||null}
async function updateLedgerConditional(id:string,from:string,patch:Record<string,unknown>){const q=`?id=eq.${encodeURIComponent(id)}&status=eq.${encodeURIComponent(from)}`;const r=await fetch(BASE+"/rest/v1/boom_media_assets"+q,{method:"PATCH",headers:svc({"content-type":"application/json",Prefer:"return=representation"}),body:JSON.stringify({...patch,updated_at:new Date().toISOString()}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error("VAULT_LEDGER_UPDATE_FAILED");const d=await r.json();if(!d?.[0])throw new Error("VAULT_STATE_CHANGED_RETRY");return d[0]}
async function signedPreview(path:string,ttl:number){const r=await fetch(`${BASE}/storage/v1/object/sign/${VAULT_BUCKET}/${encodedPath(path)}`,{method:"POST",headers:svc({"content-type":"application/json"}),body:JSON.stringify({expiresIn:ttl}),signal:AbortSignal.timeout(10000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("VAULT_SIGNED_PREVIEW_FAILED");const raw=String(d?.signedURL||d?.signedUrl||"");if(!raw)throw new Error("VAULT_SIGNED_PREVIEW_EMPTY");return raw.startsWith("http")?raw:`${BASE}/storage/v1${raw}`}
async function visualQAPlan(body:any){const mission=String(body?.mission_id||"").trim(),asset=String(body?.asset_id||"").trim();if(!mission||!asset)throw new Error("VAULT_ASSET_IDENTITY_REQUIRED");const row=await existingAsset(mission,asset);if(!row)throw new Error("VAULT_ASSET_NOT_FOUND");if(row.status!=="STORED_PENDING_QA")throw new Error("VISUAL_QA_STATUS_INVALID");return buildVisualQAPlan({mission_id:mission,asset_id:asset,storage_path:row.storage_path,reference_images:body?.reference_images||[]});}
async function analyzeVisualQA(body:any,user:any){const mission=String(body?.mission_id||"").trim(),asset=String(body?.asset_id||"").trim();if(!mission||!asset)throw new Error("VAULT_ASSET_IDENTITY_REQUIRED");if(!OPENAI_VISION_ENABLED)throw new Error("VISION_ADAPTER_DISABLED");if(!OPENAI_KEY)throw new Error("OPENAI_API_KEY_REQUIRED");const row=await existingAsset(mission,asset);if(!row)throw new Error("VAULT_ASSET_NOT_FOUND");if(row.status!=="STORED_PENDING_QA")throw new Error("VISUAL_QA_STATUS_INVALID");const request=buildOpenAIVisionRequest({frames:body?.frames,reference_images:body?.reference_images||[],product_name:body?.product_name||"",script:body?.script||"",model:OPENAI_VISION_MODEL});const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:"Bearer "+OPENAI_KEY,"content-type":"application/json"},body:JSON.stringify(request),signal:AbortSignal.timeout(45000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error("VISION_PROVIDER_FAILED_"+r.status);const parsed=parseOpenAIVisionResponse(d);const visual=evaluateVisualQA(parsed);const updated=await updateLedgerConditional(row.id,row.status,{visual_qa_json:visual,visual_qa_provider:"openai",visual_qa_model:OPENAI_VISION_MODEL,visual_qa_completed_at:new Date().toISOString(),visual_qa_updated_by:user.id});return {status:"VISUAL_QA_ANALYZED",asset_id:updated.id,vault_status:updated.status,visual_qa:visual,provider:"openai",model:OPENAI_VISION_MODEL,frame_count:Array.isArray(body?.frames)?body.frames.length:0,publishing_allowed:false};}
async function commitQA(body:any,user:any){const mission=String(body?.mission_id||"").trim(),asset=String(body?.asset_id||"").trim();if(!mission||!asset)throw new Error("VAULT_ASSET_IDENTITY_REQUIRED");const row=await existingAsset(mission,asset);if(!row)throw new Error("VAULT_ASSET_NOT_FOUND");if(["QA_PASSED","QA_FAILED","OWNER_APPROVED","REJECTED"].includes(String(row.status)))return {status:"QA_ALREADY_COMMITTED",asset_id:row.id,vault_status:row.status,qa:row.qa_json||{},publishing_allowed:false};if(row.status!=="STORED_PENDING_QA")throw new Error("VAULT_QA_STATUS_INVALID");const evidence={...(body?.evidence||{}),stored_private:true,aspect_ratio:row.aspect_ratio,duration_seconds:Number(row.duration_seconds),visual_qa_passed:row?.visual_qa_json?.status==="VISUAL_QA_PASSED"};const qa=postGenerationQA(evidence);assertTransition(row.status,qa.status);const updated=await updateLedgerConditional(row.id,row.status,{status:qa.status,qa_json:qa,qa_completed_at:new Date().toISOString(),qa_updated_by:user.id});return {status:"QA_COMMITTED",asset_id:updated.id,vault_status:updated.status,qa,publishing_allowed:false,owner_approval_required:true}}
async function commitOwnerDecision(body:any,user:any){const mission=String(body?.mission_id||"").trim(),asset=String(body?.asset_id||"").trim();if(!mission||!asset)throw new Error("VAULT_ASSET_IDENTITY_REQUIRED");const decision=ownerDecision(body?.decision),note=decisionNote(body?.note);const row=await existingAsset(mission,asset);if(!row)throw new Error("VAULT_ASSET_NOT_FOUND");if(decision==="approve"&&row.status==="OWNER_APPROVED")return {status:"OWNER_DECISION_ALREADY_COMMITTED",asset_id:row.id,vault_status:row.status,decision:"approve",publishing_allowed:false};if(decision==="reject"&&row.status==="REJECTED")return {status:"OWNER_DECISION_ALREADY_COMMITTED",asset_id:row.id,vault_status:row.status,decision:"reject",publishing_allowed:false};const to=decision==="approve"?"OWNER_APPROVED":"REJECTED";assertTransition(String(row.status),to);const now=new Date().toISOString();const patch:any={status:to,owner_decision_by:user.id,owner_decision_note:note,owner_decided_at:now};if(to==="OWNER_APPROVED")patch.owner_approved_at=now;const updated=await updateLedgerConditional(row.id,String(row.status),patch);return {status:"OWNER_DECISION_COMMITTED",asset_id:updated.id,vault_status:updated.status,decision,owner_decided_at:now,publishing_allowed:false,next_safe_action:decision==="approve"?"Asset is Owner-approved for a separate publish workflow. Publishing remains disabled here.":"Asset is rejected and cannot publish."}}
async function ingestRunway(body:any,user:any){const taskId=validateTaskId(body?.task_id);const mission=String(body?.asset?.mission_id||"").trim(),assetId=String(body?.asset?.asset_id||"").trim();if(!mission||!assetId)throw new Error("VAULT_ASSET_IDENTITY_REQUIRED");const prior=await existingAsset(mission,assetId);if(prior)return {status:"ALREADY_INGESTED",asset_id:prior.id,vault_status:prior.status,storage_path:prior.storage_path,sha256:prior.sha256,public_url:null,publishing_allowed:false};const output=await runwayOutput(taskId);const media=await downloadVideo(output);const plan=planVaultAsset({...body.asset,generation_completed:true,mime_type:media.mime});await uploadPrivate(plan.storage_path,media);try{const row=await insertLedger({mission_id:mission,creative_asset_id:plan.creative_asset_id,product_item_id:String(body.asset.product_item_id),product_variant_id:body.asset.product_variant_id||null,source_provider:"runway-gen45",provider_task_id:taskId,provider_output_index:0,storage_bucket:VAULT_BUCKET,storage_path:plan.storage_path,media_kind:"video",mime_type:media.mime,byte_size:media.size,duration_seconds:Number(body.asset.duration_seconds),aspect_ratio:"9:16",sha256:media.sha256,prompt_hash:body.asset.prompt_hash||null,product_truth_verified_at:body.asset.product_truth_verified_at,status:"STORED_PENDING_QA",created_by:user.id,ingested_at:new Date().toISOString()});return {status:"INGESTED_PRIVATE",asset_id:row?.id||null,vault_status:"STORED_PENDING_QA",storage_path:plan.storage_path,sha256:media.sha256,byte_size:media.size,public_url:null,publishing_allowed:false,next_safe_action:"Run post-generation QA, then Owner review."}}catch(e){await deletePrivate(plan.storage_path);throw e}}
Deno.serve(async req=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});
  if(req.method!=="POST")return json(req,{error:"POST_ONLY"},405);
  const user=await userFromReq(req);if(!user||!(await isAdmin(user.id)))return json(req,{error:"OWNER_ADMIN_REQUIRED"},403);
  const body=await req.json().catch(()=>({}));const action=String(body?.action||"preview_asset");
  try{
    if(action==="readiness")return json(req,{status:"MEDIA_VAULT_READINESS",vault_runtime_active:true,runway_secret_present:Boolean(RUNWAY_SECRET),vision_enabled:OPENAI_VISION_ENABLED,vision_secret_present:Boolean(OPENAI_KEY),vision_model:OPENAI_VISION_MODEL,secret_values_exposed:false,publishing_allowed:false});
    if(action==="preview_asset")return json(req,{status:"VAULT_PLAN",...planVaultAsset(body?.asset)});
    if(action==="ingest_runway")return json(req,await ingestRunway(body,user));
    if(action==="private_preview"){const mission=String(body?.mission_id||"").trim(),asset=String(body?.asset_id||"").trim();const row=await existingAsset(mission,asset);if(!row||row.status==="GENERATED_PENDING_INGEST")return json(req,{error:"VAULT_ASSET_NOT_STORED"},404);const ttl=previewTTL(body?.ttl_seconds??60);const url=await signedPreview(row.storage_path,ttl);return json(req,{status:"PRIVATE_PREVIEW_READY",asset_id:row.id,vault_status:row.status,signed_url:url,expires_in_seconds:ttl,qa:row.qa_json||{},public_url:null,publishing_allowed:false});}
    if(action==="visual_qa_plan")return json(req,await visualQAPlan(body));
    if(action==="visual_qa_analyze")return json(req,await analyzeVisualQA(body,user));
    if(action==="qa_preview")return json(req,postGenerationQA(body?.evidence||{}));
    if(action==="qa_commit")return json(req,await commitQA(body,user));
    if(action==="owner_decision")return json(req,await commitOwnerDecision(body,user));
    if(action==="transition_preview"){assertTransition(String(body?.from||""),String(body?.to||""));return json(req,{status:"TRANSITION_ALLOWED",from:body.from,to:body.to,executed:false});}
    return json(req,{error:"ACTION_UNSUPPORTED"},400);
  }catch(e){return json(req,{error:e instanceof Error?e.message:String(e)},400)}
});
