-- Intentionally left as a no-op.
-- The unique index on (provider, provider_event_id) is created by
-- 20260915090100_hunt_order_pipeline_prelaunch.sql.
-- Keeping this migration version preserves applied migration history
-- without rebuilding the same index or blocking payment-event writes.
