-- BOOM Professional Human Ground Truth / Annotation Ledger
-- SOURCE ONLY until explicitly applied. No Production, payment, supplier or publish activation.
-- Human labels are append-only evidence used to calibrate automated evaluators.

create table if not exists public.hunt_boom_human_labels (
  id bigint generated by default as identity primary key,
  evaluator_id bigint not null references public.hunt_boom_evaluator_registry(id) on delete restrict,
  observation_id bigint references public.hunt_boom_model_observations(id) on delete set null,
  trace_ref text,
  route_key text,
  rubric_key text not null,
  automated_label text check (automated_label is null or automated_label in ('pass','fail','abstain','unmeasured')),
  automated_score numeric(6,5) check (automated_score is null or (automated_score >= 0 and automated_score <= 1)),
  human_label text not null check (human_label in ('pass','fail','uncertain')),
  human_score numeric(6,5) check (human_score is null or (human_score >= 0 and human_score <= 1)),
  rationale text check (rationale is null or char_length(rationale) <= 2000),
  correction text check (correction is null or char_length(correction) <= 4000),
  reviewer_id uuid not null references auth.users(id) on delete restrict,
  metadata jsonb not null default '{}'::jsonb,
  reviewed_at timestamptz not null default now(),
  constraint hunt_boom_human_labels_evidence_ref_check
    check (observation_id is not null or nullif(btrim(trace_ref),'') is not null)
);

create unique index if not exists hunt_boom_human_labels_observation_reviewer_uidx
  on public.hunt_boom_human_labels(evaluator_id,observation_id,reviewer_id,rubric_key)
  where observation_id is not null;

create index if not exists hunt_boom_human_labels_evaluator_idx
  on public.hunt_boom_human_labels(evaluator_id,reviewed_at desc);

create index if not exists hunt_boom_human_labels_observation_idx
  on public.hunt_boom_human_labels(observation_id)
  where observation_id is not null;

alter table public.hunt_boom_human_labels enable row level security;

revoke all on table public.hunt_boom_human_labels from anon, authenticated;
grant select, insert on table public.hunt_boom_human_labels to authenticated;
grant all on table public.hunt_boom_human_labels to service_role;

drop policy if exists "Admins read hunt_boom_human_labels" on public.hunt_boom_human_labels;
create policy "Admins read hunt_boom_human_labels"
on public.hunt_boom_human_labels
for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and p.is_admin=true
  )
);

drop policy if exists "Admins append hunt_boom_human_labels" on public.hunt_boom_human_labels;
create policy "Admins append hunt_boom_human_labels"
on public.hunt_boom_human_labels
for insert to authenticated
with check (
  reviewer_id=(select auth.uid())
  and exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and p.is_admin=true
  )
);

comment on table public.hunt_boom_human_labels is
  'Append-only human annotation evidence for evaluator calibration. No authenticated UPDATE/DELETE grants.';
