-- BOOM Professional Read-Only Observability Cell
-- SOURCE ONLY until explicitly applied. Does not activate monitors, schedules, Production or mutations.
-- Separate evidence lanes: health, security, performance, capacity.

create table if not exists public.hunt_boom_observability_snapshots (
  id bigint generated by default as identity primary key,
  monitor_type text not null check (monitor_type in ('health','security','performance','capacity')),
  project_ref text not null,
  observed_at timestamptz not null,
  window_start timestamptz,
  window_end timestamptz,
  state text not null check (state in ('clear','watch','critical','unable_to_assess')),
  findings_count integer not null default 0 check (findings_count >= 0),
  unavailable_checks integer not null default 0 check (unavailable_checks >= 0),
  evidence jsonb not null default '{}'::jsonb,
  evidence_fingerprint text,
  source_ref text,
  review_required boolean not null default false,
  created_at timestamptz not null default now(),
  constraint hunt_boom_observability_window_check
    check (window_start is null or window_end is null or window_end >= window_start)
);

create index if not exists hunt_boom_observability_snapshots_type_time_idx
  on public.hunt_boom_observability_snapshots(monitor_type,observed_at desc);

create index if not exists hunt_boom_observability_snapshots_review_idx
  on public.hunt_boom_observability_snapshots(review_required,observed_at desc)
  where review_required=true;

alter table public.hunt_boom_observability_snapshots enable row level security;

revoke all on table public.hunt_boom_observability_snapshots from anon, authenticated;
grant select on table public.hunt_boom_observability_snapshots to authenticated;
grant all on table public.hunt_boom_observability_snapshots to service_role;

drop policy if exists "Admins read hunt_boom_observability_snapshots" on public.hunt_boom_observability_snapshots;
create policy "Admins read hunt_boom_observability_snapshots"
on public.hunt_boom_observability_snapshots
for select to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id=(select auth.uid()) and p.is_admin=true
  )
);

comment on table public.hunt_boom_observability_snapshots is
  'Append-only read-only observability evidence for BOOM Health, Security, Performance and Capacity monitors.';
